SELECT [IdIntercambio]
      ,[TipoIntercambio]
      ,[Proyecto]
      ,[Institucion]
      ,[Direccion]
      ,[Ciudad]
      ,[Pais]
      ,[Telefono]
      ,[Fax]
      ,[E-mail]
      ,[PaginaWeb]
      ,[Codigo]
      ,[Responsable]
      ,[Contacto]
      ,[TextoNoContacto]
  FROM [C:\TECNOLOGIASAPROPIADAS\APP_DATA\TECNOLOGIASAPROPIADA.MDF].[dbo].[Intercambio]

